kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: arbeidssokerregistrering-veileder
  namespace: paw
  labels:
    team: paw
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.01.03_14.26-195302823f9a
  port: 8080
  ingresses:
    - https://arbeidssokerregistrering.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: false
    path: /internal/metrics
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: arbeidssokerregistrering-veileder-dev
        cascadingDelete: false
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      errorPath: "feilsti-ikke-konfigurert"
  accessPolicy:
    outbound:
      rules:
        - application: paw-proxy
          cluster: dev-fss
          namespace: paw
        - application: pam-janzz
          namespace: teampam
      external:
        - host: paw-proxy.dev-fss-pub.nais.io
        - host: unleash.nais.io

  env:
    - name: PAM_JANZZ_URL
      value: https://pam-janzz.intern.nav.no/pam-janzz/rest
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "arbeidssokerregistrering-veileder-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "fallbackStrategy":  "NONE",
           "redirects": [
             {
                "fromPath": "/pam-janzz",
                "toUrl": "https://pam-janzz.intern.nav.no/pam-janzz/rest",
                "preserveFromPath": false
             }
           ],
          "proxies": [
            {
              "fromPath": "/veilarbregistrering",
              "toUrl": "https://paw-proxy.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": { "name": "paw-proxy", "namespace": "paw", "cluster": "dev-fss" }
            }
          ]
        }
